# nixpacks.toml

[phases.setup]
  # Add any extra dependencies here (e.g., system packages)

[phases.install]
  cmds = ["pip install -r requirements.txt"]

[start]
  cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"

