[project]
name = "yt-dub-backend"
language = "python"

[phases.setup]
packages = ["ffmpeg", "python3", "python3Packages.pip", "python3Packages.numpy", "python3Packages.librosa"]

[phases.install]
commands = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.start]
commands = [
  "gunicorn --bind 0.0.0.0:$PORT app:app"
]
